"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.s3_location import S3Location
globals()['S3Location'] = S3Location
from openapi_client.model.credentials_request import CredentialsRequest


class TestCredentialsRequest(unittest.TestCase):
    """CredentialsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredentialsRequest(self):
        """Test CredentialsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CredentialsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
