"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.s3_location import S3Location


class TestS3Location(unittest.TestCase):
    """S3Location unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS3Location(self):
        """Test S3Location"""
        # FIXME: construct object with mandatory attributes with example values
        # model = S3Location()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
