"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.possible_rocrate import PossibleRocrate
globals()['PossibleRocrate'] = PossibleRocrate
from openapi_client.model.response_convert_collection_format_rocrate import ResponseConvertCollectionFormatRocrate


class TestResponseConvertCollectionFormatRocrate(unittest.TestCase):
    """ResponseConvertCollectionFormatRocrate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseConvertCollectionFormatRocrate(self):
        """Test ResponseConvertCollectionFormatRocrate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseConvertCollectionFormatRocrate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
