"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.input_convert_rocrate_collection_format import InputConvertRocrateCollectionFormat


class TestInputConvertRocrateCollectionFormat(unittest.TestCase):
    """InputConvertRocrateCollectionFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInputConvertRocrateCollectionFormat(self):
        """Test InputConvertRocrateCollectionFormat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InputConvertRocrateCollectionFormat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
