"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.collection_format_author import CollectionFormatAuthor
from openapi_client.model.collection_format_dataset_info import CollectionFormatDatasetInfo
globals()['CollectionFormatAuthor'] = CollectionFormatAuthor
globals()['CollectionFormatDatasetInfo'] = CollectionFormatDatasetInfo
from openapi_client.model.collection_format import CollectionFormat


class TestCollectionFormat(unittest.TestCase):
    """CollectionFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollectionFormat(self):
        """Test CollectionFormat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CollectionFormat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
