"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_data_api
from rrap_mds_is_data_api.model.collection_format_organisation import CollectionFormatOrganisation
globals()['CollectionFormatOrganisation'] = CollectionFormatOrganisation
from rrap_mds_is_data_api.model.collection_format_author import CollectionFormatAuthor


class TestCollectionFormatAuthor(unittest.TestCase):
    """CollectionFormatAuthor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollectionFormatAuthor(self):
        """Test CollectionFormatAuthor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CollectionFormatAuthor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
