"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.registry_item import RegistryItem
from openapi_client.model.status import Status
globals()['RegistryItem'] = RegistryItem
globals()['Status'] = Status
from openapi_client.model.registry_parsed_export import RegistryParsedExport


class TestRegistryParsedExport(unittest.TestCase):
    """RegistryParsedExport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistryParsedExport(self):
        """Test RegistryParsedExport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegistryParsedExport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
