"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.credentials import Credentials
from openapi_client.model.status import Status
globals()['Credentials'] = Credentials
globals()['Status'] = Status
from openapi_client.model.credential_response import CredentialResponse


class TestCredentialResponse(unittest.TestCase):
    """CredentialResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredentialResponse(self):
        """Test CredentialResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CredentialResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
