"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.possible_rocrate import PossibleRocrate


class TestPossibleRocrate(unittest.TestCase):
    """PossibleRocrate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPossibleRocrate(self):
        """Test PossibleRocrate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PossibleRocrate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
