"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.metadata_api import MetadataApi  # noqa: E501


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self):
        self.api = MetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_dataset_schema_metadata_dataset_schema_get(self):
        """Test case for get_dataset_schema_metadata_dataset_schema_get

        Get Dataset Schema  # noqa: E501
        """
        pass

    def test_validate_metadata_metadata_validate_metadata_post(self):
        """Test case for validate_metadata_metadata_validate_metadata_post

        Validate Metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
