"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.collection_format_conversion import CollectionFormatConversion
globals()['CollectionFormatConversion'] = CollectionFormatConversion
from openapi_client.model.input_convert_collection_format_rocrate import InputConvertCollectionFormatRocrate


class TestInputConvertCollectionFormatRocrate(unittest.TestCase):
    """InputConvertCollectionFormatRocrate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInputConvertCollectionFormatRocrate(self):
        """Test InputConvertCollectionFormatRocrate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InputConvertCollectionFormatRocrate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
