"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.administration_api import AdministrationApi  # noqa: E501


class TestAdministrationApi(unittest.TestCase):
    """AdministrationApi unit test stubs"""

    def setUp(self):
        self.api = AdministrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_convert_collection_format_rocrate_admin_registry_convert_collection_format_ro_crate_post(self):
        """Test case for convert_collection_format_rocrate_admin_registry_convert_collection_format_ro_crate_post

        Convert Collection Format Rocrate  # noqa: E501
        """
        pass

    def test_convert_rocrate_collection_format_admin_registry_convert_rocrate_collection_format_post(self):
        """Test case for convert_rocrate_collection_format_admin_registry_convert_rocrate_collection_format_post

        Convert Rocrate Collection Format  # noqa: E501
        """
        pass

    def test_export_registry_parsed_admin_registry_export_parsed_get(self):
        """Test case for export_registry_parsed_admin_registry_export_parsed_get

        Export Registry Parsed  # noqa: E501
        """
        pass

    def test_export_registry_unparsed_admin_registry_export_unparsed_get(self):
        """Test case for export_registry_unparsed_admin_registry_export_unparsed_get

        Export Registry Unparsed  # noqa: E501
        """
        pass

    def test_import_registry_parsed_admin_registry_import_parsed_post(self):
        """Test case for import_registry_parsed_admin_registry_import_parsed_post

        Import Registry Parsed  # noqa: E501
        """
        pass

    def test_import_registry_unparsed_admin_registry_import_unparsed_post(self):
        """Test case for import_registry_unparsed_admin_registry_import_unparsed_post

        Import Registry Unparsed  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
