"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_data_api
from rrap_mds_is_data_api.model.schema import Schema


class TestSchema(unittest.TestCase):
    """Schema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchema(self):
        """Test Schema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Schema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
