"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_data_api
from rrap_mds_is_data_api.model.registry_item import RegistryItem
from rrap_mds_is_data_api.model.status import Status
globals()['RegistryItem'] = RegistryItem
globals()['Status'] = Status
from rrap_mds_is_data_api.model.list_registry_response import ListRegistryResponse


class TestListRegistryResponse(unittest.TestCase):
    """ListRegistryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListRegistryResponse(self):
        """Test ListRegistryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListRegistryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
