"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_data_api
from rrap_mds_is_data_api.model.collection_format_organisation import CollectionFormatOrganisation


class TestCollectionFormatOrganisation(unittest.TestCase):
    """CollectionFormatOrganisation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollectionFormatOrganisation(self):
        """Test CollectionFormatOrganisation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CollectionFormatOrganisation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
