"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_data_api
from rrap_mds_is_data_api.model.import_statistics import ImportStatistics
from rrap_mds_is_data_api.model.status import Status
globals()['ImportStatistics'] = ImportStatistics
globals()['Status'] = Status
from rrap_mds_is_data_api.model.import_response import ImportResponse


class TestImportResponse(unittest.TestCase):
    """ImportResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportResponse(self):
        """Test ImportResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImportResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
