"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rrap_mds_is_data_api
from rrap_mds_is_data_api.api.registry_items_api import RegistryItemsApi  # noqa: E501


class TestRegistryItemsApi(unittest.TestCase):
    """RegistryItemsApi unit test stubs"""

    def setUp(self):
        self.api = RegistryItemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_dataset(self):
        """Test case for fetch_dataset

        Fetch Dataset  # noqa: E501
        """
        pass

    def test_list_all_datasets(self):
        """Test case for list_all_datasets

        List All Datasets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
