"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rrap_mds_is_data_api
from rrap_mds_is_data_api.api.administration_api import AdministrationApi  # noqa: E501


class TestAdministrationApi(unittest.TestCase):
    """AdministrationApi unit test stubs"""

    def setUp(self):
        self.api = AdministrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_convert_from_collection_format_to_ro_crate(self):
        """Test case for convert_from_collection_format_to_ro_crate

        Convert Collection Format Rocrate  # noqa: E501
        """
        pass

    def test_convert_from_ro_crate_to_collection_format(self):
        """Test case for convert_from_ro_crate_to_collection_format

        Convert Rocrate Collection Format  # noqa: E501
        """
        pass

    def test_export_parsed(self):
        """Test case for export_parsed

        Export Registry Parsed  # noqa: E501
        """
        pass

    def test_export_unparsed(self):
        """Test case for export_unparsed

        Export Registry Unparsed  # noqa: E501
        """
        pass

    def test_import_parsed(self):
        """Test case for import_parsed

        Import Registry Parsed  # noqa: E501
        """
        pass

    def test_import_unparsed(self):
        """Test case for import_unparsed

        Import Registry Unparsed  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
