"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import rrap_mds_is_data_api
from rrap_mds_is_data_api.api.registry_credentials_api import RegistryCredentialsApi  # noqa: E501


class TestRegistryCredentialsApi(unittest.TestCase):
    """RegistryCredentialsApi unit test stubs"""

    def setUp(self):
        self.api = RegistryCredentialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_read_access_credentials(self):
        """Test case for generate_read_access_credentials

        Generate Read Access Credentials  # noqa: E501
        """
        pass

    def test_generate_write_access_credentials(self):
        """Test case for generate_write_access_credentials

        Generate Write Access Credentials  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
