"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rrap_mds_is_data_api
from rrap_mds_is_data_api.model.registry_item import RegistryItem
globals()['RegistryItem'] = RegistryItem
from rrap_mds_is_data_api.model.registry_parsed_import import RegistryParsedImport


class TestRegistryParsedImport(unittest.TestCase):
    """RegistryParsedImport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistryParsedImport(self):
        """Test RegistryParsedImport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegistryParsedImport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
