# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from openapi_client.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from openapi_client.model.collection_format import CollectionFormat
from openapi_client.model.collection_format_author import CollectionFormatAuthor
from openapi_client.model.collection_format_conversion import CollectionFormatConversion
from openapi_client.model.collection_format_dataset_info import CollectionFormatDatasetInfo
from openapi_client.model.collection_format_organisation import CollectionFormatOrganisation
from openapi_client.model.credential_response import CredentialResponse
from openapi_client.model.credentials import Credentials
from openapi_client.model.credentials_request import CredentialsRequest
from openapi_client.model.http_validation_error import HTTPValidationError
from openapi_client.model.import_response import ImportResponse
from openapi_client.model.import_statistics import ImportStatistics
from openapi_client.model.input_convert_collection_format_rocrate import InputConvertCollectionFormatRocrate
from openapi_client.model.input_convert_rocrate_collection_format import InputConvertRocrateCollectionFormat
from openapi_client.model.list_registry_response import ListRegistryResponse
from openapi_client.model.location_inner import LocationInner
from openapi_client.model.mint_response import MintResponse
from openapi_client.model.possible_collection_format import PossibleCollectionFormat
from openapi_client.model.possible_rocrate import PossibleRocrate
from openapi_client.model.registry_fetch_response import RegistryFetchResponse
from openapi_client.model.registry_item import RegistryItem
from openapi_client.model.registry_parsed_export import RegistryParsedExport
from openapi_client.model.registry_parsed_import import RegistryParsedImport
from openapi_client.model.registry_unparsed_export import RegistryUnparsedExport
from openapi_client.model.registry_unparsed_import import RegistryUnparsedImport
from openapi_client.model.response_convert_collection_format_rocrate import ResponseConvertCollectionFormatRocrate
from openapi_client.model.response_convert_rocrate_collection_format import ResponseConvertRocrateCollectionFormat
from openapi_client.model.s3_location import S3Location
from openapi_client.model.schema import Schema
from openapi_client.model.status import Status
from openapi_client.model.update_metadata_response import UpdateMetadataResponse
from openapi_client.model.user import User
from openapi_client.model.validation_error import ValidationError
